### PR TITLE
CURA-4790 If using "bold", use .setBold(), else use .setWeight()

### PR DESCRIPTION
**Pull request by ianpaschal**
Based on feedback from @fieldOfView.

### CODE REVIEW

**Comment by fieldOfView** [comment]
I would do it the other way around though; have the (more specific) weight override bold, if they are both specified.

**Comment by ianpaschal** [comment]
I went back and forth but decided to make weight the default as every font has "some weight," but not every font has "bold." To me, the default should be some value, not the lack of an extra property. "Bold" is the override to "normal" similar to "italic."

I don't think there's a technical issue to either one, it's just preference.

**Comment by fieldOfView** [comment]
Most - if not all - of the fonts I have installed have a bold, and only the expensive ones have different weights. But it is not critical, as long as either of them works.

**Comment by ianpaschal** [comment]
Actually every font has weight(s). "Bold" is merely a shorthand for "700". The expensive ones just have more weights than 400 and 700. The fact that you can set the weight and bold properties is more a product of not many programmers being typographers. While we're at it, "font family" should really be referred to as "typeface". But whatever, haha.

But yeah, since I think it's personal preference, I'm going to consider this reviewed and merge. If we find a reason in the future to switch it back... well... we'll code that bridge when get to it.

**Pull request merged**
