### PR TITLE
Rounding caused characters to be misaligned

### PR DESCRIPTION
**Pull request by Appesteijn**
Together with Cura PR: https://github.com/Ultimaker/Cura/pull/2586

CURA-4437

### CODE REVIEW

**Comment by ChrisTerBeke** [comment]
@fieldOfView do you have any ideas on how to fix this? Using int will fix the 'wavy font' issue on MacOS but causes a lot of issues on Windows. We suspect the issue is still somewhere in conversion from points to actual pixels in the font rendering.

**Comment by Appesteijn** [comment]
This is how it looked before this PR (with the Round function):
screen shot 2017-10-11 at 14 23 12

And this is how it looks on Mac after this PR (wit cast to int):
screen shot 2017-10-11 at 14 21 55

**Comment by fieldOfView** [comment]
Try int(round()) instead of int()

**Comment by ChrisTerBeke** [comment]
int(rount()) works like a charm on my machine.

**Comment by ChrisTerBeke** [comment]
Apparently it does not work on retina macbook....

**Comment by Appesteijn** [comment]
Same output on MacOS as in screenshot above :(

**Comment by fieldOfView** [comment]
The only logical conclusion is that the "fix" proposed in the two PRs is purely symptomatic. I think there is still a fractional offset somewhere that is causing the actual issue, but the font rendering on OSX just so happens to round it the proper way when one (or more) of the other sizes are rounded down by a pixel.

**Comment by fieldOfView** [comment]
Note how the printer dropdown renders the text correctly in both screenshots. It could be either the left margin of the other elements, or a vertical size somewhere.

**Comment by fieldOfView** [comment]
Ok, I think I have found the culprit, but I have no way to check on a retina mac.
https://github.com/Ultimaker/Cura/blob/master/resources/qml/SidebarHeader.qml#L20
This should be rounded, or every item but the first item is going to be on a non-integer y offset.

On a personal note: this is not how you do theming; getting a size from the theme and then multiplying it by a magic number.

**Comment by Appesteijn** [comment]
I fixed that but it didn't solve it

**Comment by fieldOfView** [comment]
In SidebarHeader alone, I see a number of other offenders (height * 2 / 3, width * 0.7)

**Comment by Appesteijn** [comment]
These should now be fixed with a Math.floor()

**Pull request closed without merging**
