### PR TITLE
Preferences: Making note about deprecation more clear

### PR DESCRIPTION
**Pull request by thopiekar**
Now the developer knows which trivial change needs to be done.

### CODE REVIEW

**Comment by nallath** [comment]
Except that getPreferences() isnt a class function, so it should be Application.getInstance().getPreferences()

**Comment by fieldOfView** [comment]
I don't agree with the revised text; it instructs the developer to change Preferences.py ("please change this function").

**Comment by fieldOfView** [comment]
```Please use Application.getInstance().getPreferences() instead of Preferences.getInstance()```

**Comment by thopiekar** [comment]
Oh, yes, that's correct @nallath

@fieldOfView: Can't follow on this. I'm recommending to replace one function call with another. I don't see where I tell someone to modify Preferences.py 🤷

**Comment by fieldOfView** [comment]
The word "this" refers to something very close to the word this (as opposed to "that", which refers to something further away). The closest thing to what you refer to is the actual getInstance() method text. So you are telling me to replace the code of the Preferences.getInstance() method with the code of the Application.getInstance().getPreferences() method. Which to me is more confusing than the original text.

By using "use" instead of "replace with", you prevent that whole confusion.

**Comment by thopiekar** [comment]
To be honest, I'm confused by this confusion now. I mean why should someone modify files delivered by Cura? 😅
But you are right with this. By choosing the correct words it is definite without exceptions.

**Comment by nallath** [comment]
How about: @deprecated("Please use Application.getInstance().getPreferences() instead", "3.3")

**Comment by nallath** [comment]
Fixed it in a53d0c37cacf0935105212b654b9604b212f405c

**Pull request closed without merging**
