### PR TITLE
Czech translations v4.12.1

### PR DESCRIPTION
**Pull request by sustmi**

### CODE REVIEW

**Comment by nallath** [comment]
I changed the branch back to master again, since we already released 4.12

**Review by nallath — APPROVED** [review]
I checked the translation with one of our engineers that speaks Czech.

**Comment by Ghostkeeper** [comment]
This is the same person that normally translates Cura for us. They apologised for being late, and hopes to be less busy next time :)

**Comment by nallath** [comment]
Whoops! I forgot to merge this. My bad :(

**Pull request merged**
