### PR TITLE
UM.Application: Remove Unity workaround

### PR DESCRIPTION
**Pull request by thopiekar**
Just found this workaround between regular code.
I would prefer to move the workaround to all the other workarounds at cura_app.py.

### CODE REVIEW

**Comment by Ghostkeeper** [comment]
I need this workaround :(
If it is preferred to move the workaround to similar code, don't just delete it but add it back among the other code too!

**Comment by Ghostkeeper** [comment]
Ah, I see it was added back in a different pull request. Sorry!

It would've made sense to make this one pull request though. One should not be accepted without the other. I'll test both changes and see if the behaviour is still correct.

**Comment by Ghostkeeper** [comment]
Ah, I see that the code was added back in the Cura repository rather than the Uranium repository.

This would break the other applications that depend on Uranium though. This workaround is not specific to Cura.

**Comment by thopiekar** [comment]
But I would like to collect all work at one place.
I personally don't like to have all the hacks flying around. 😒
This one for example is not marked or whatsoever.
Maybe we should decide to move all workarounds to Uranium then? The NVidia workaround should also be useful for Uranium, too.

**Comment by Ghostkeeper** [comment]
I agree that the NVidia workaround should've been put in Uranium.

We may still have workarounds that are specific to Cura though. For instance if there's anything necessary to make USB printing work. I think we should strive to put the workarounds in the modules that concern them: USB printing workarounds in the USB printing plug-in, rendering workarounds in the rendering code, Unity GUI workarounds in the Qt code, etc.

**Pull request closed without merging**
