### PR TITLE
Change text requested by MJ

### PR DESCRIPTION
**Pull request by Appesteijn**

### CODE REVIEW

**Comment by fieldOfView** [comment]
The .pot file is automatically generated. There's little sense in changing the text there. Change the text in UpdateCheckerJob.py instead (as you did for some strings, but not all).

**Comment by Appesteijn** [comment]
Don't want to change the application name to Ultimaker Cura because I don't know what other things will break then..

**Comment by nallath** [comment]
Changing the application name to Ultimaker Cura is a really bad idea. That would have broken a lot of resource loading stuff.

**Comment by fieldOfView** [comment]
Note that I did not suggest in any way that the application_name should be changed (please, no!), but you changed one occurrence of Cura into Ultimaker Cura in the .pot that you did not change in the .py (and changing them in the .pot has no effect anyway). ```Cura {0} is available!```

**Comment by diegopradogesto** [comment]
Closing this PR in favor of https://github.com/Ultimaker/Uranium/pull/413

**Pull request closed without merging**
