### PR TITLE
Added Polish translation

### PR DESCRIPTION
**Pull request by MarPiRK**
Also changed formatting of long representation of print time – not it uses plural forms. I'm not sure if it's the best way to do it. Feel free to change it. Unfortunately it required updating `pot` file, so it's a little bit messy.

### CODE REVIEW

**Comment by Ghostkeeper** [comment]
It's almost as if you knew that we're entering a string freeze on the next version this weekend... Lucky!

I understand that the changes are because you re-generated the strings from our code. But that makes me wonder why it still says that the files originate from my home folder :stuck_out_tongue:

**Comment by MarPiRK** [comment]
Hah, got that timing 😂

About paths I just wanted to change least lines as possible. Turns out that it didn't really help, so whatever.

**Comment by Ghostkeeper** [comment]
What I do need to ask though is what application you intended to write these translations for. This is only Uranium, and the translations will be incomplete if you intend to translate Cura or NinjaKittens2.

**Comment by MarPiRK** [comment]
Sure enough, I'm planning to translate entire Cura and I'm on the way, but as you might know it's sth like 1000 sentences. Uranium is the first step.

**Comment by Ghostkeeper** [comment]
I know. Don't underestimate that FDMPrinter file...

**Comment by MarPiRK** [comment]
So will this be merged?

**Comment by thopiekar** [comment]
So the answer is yes :wink:

**Comment by MarPiRK** [comment]
Thanks :smile:

**Comment by Ghostkeeper** [comment]
It's not active yet in any application though.

**Comment by thopiekar** [comment]
@MarPiRK, according to https://translations.launchpad.net/uranium/trunk/+pots/uranium/pl/+translate there are missing translations.
So if you like you can continue translating Uranium here or please update your translation via Git.
Additionally if you like to use launchpad to translate Cura, just create a PR with empty strings.

Regards

**Pull request merged**
