### PR TITLE
CURA-5538 Fix intersection function

### PR DESCRIPTION
**Pull request by LipuFei**
Home made solution has bugs. For example, if it's processing two almost identical rectangles (e.g. with 0.0001 differences), then it can return an empty Polygon, indicating that there is no intersection.

Companion PR: https://github.com/Ultimaker/cura-build/pull/184

### CODE REVIEW

**Comment by LipuFei** [comment]
The jenkins error should be gone once the companion PRs get merged.

**Comment by LipuFei** [comment]
Closed the wrong PR...

**Comment by ianpaschal** [comment]
screen shot 2018-08-08 at 14 01 19

😍

**Comment by thopiekar** [comment]
Btw. that means for me that there is a new dependency I need to add to PPA packages right?

**Comment by LipuFei** [comment]
@thopiekar Actually 2, `trimesh` and `shapely`

**Comment by LipuFei** [comment]
Well, trimesh is not used at the moment, so you can skip it.

**Comment by ianpaschal** [comment]
Well, we did decide today in Cookies & Cura that we're going to attempt to use Trimesh, so I'd include it @thopiekar

**Comment by thopiekar** [comment]
Ok, shapely is included in Ubuntu's repository. Any minimum version we need?
And for trimesh I will need to make packaging files. Couldn't find it in Debian's repo either 🤔

**Comment by LipuFei** [comment]
@thopiekar `shapely 1.6.4` and `trimesh 2.31.45`, see https://github.com/Ultimaker/cura-build-environment/pull/43

**Comment by thopiekar** [comment]
Alright. Thank you for the summary.

In case the older version doesn't work I'll add an updated package then. 😉

**Comment by LipuFei** [comment]
I did a few more refactor.

**Pull request merged**
