### PR TITLE
PointingRectangle border

### PR DESCRIPTION
**Pull request by fieldOfView**
This PR implements a true border for UM.PointingRectangle. Since I introduced the PointingRectangle it has always irked me that I needed to add two PointingRectangles to draw one with a border, and hope the second one always nicely aligns with the first one. Now a PointingRectangle can draw its own border, like it should.

### CODE REVIEW

**Comment by fieldOfView** [comment]
Thinking about PointingRectangle, shouldn't it be moved into Cura instead of Uranium?

**Comment by nallath** [comment]
Argus also uses the PointingRectangle, so it's fine to leave it there.

**Comment by Ghostkeeper** [comment]
Devs, see CURA-3994.

**Comment by fieldOfView** [comment]
See https://github.com/Ultimaker/Cura/pull/2059, which depends on this PR.

**Comment by BagelOrb** [comment]
Can somebody explain to me how a rectangle can be pointing?!
It's too symmetrical to be an arrow!

**Comment by fieldOfView** [comment]
1rycmk

The PointingRectangle has been a thing since before Cura 2.1. It is a rectangle with a triangle affixed to it. But RectangleWithPointingTriangleAffixedToIt is such a long name.

**Comment by nallath** [comment]
I think we can't use Rectangle+Triangle as a class name either.

**Comment by BagelOrb** [comment]
I wasn't sure if I was serious or trolling myself. Is both possible?
What about ClassForRepresentingNearlyRectangularBoxesIfItWereNotForTheLittleTriangleThatIsAffixedToIt?

**Pull request merged**
