### PR TITLE
Plugin refactor

### PR DESCRIPTION
**Pull request by ianpaschal**
I've consolidated a lot of functionality within the plugin registry and as far as I can tell, everything is still working, but this is why I wanted to talk with Terri about being better able to know if something is going to fail tests.

### CODE REVIEW

**Comment by fieldOfView** [comment]
Something I did not catch before is that you this changed the the Plugins page in Uranium. The page now refers to the Plugin Browser, but the plugin browser only exists in Cura. There are other applications that use Uranium that do not have a plugin browser, and are now not able to manage their plugins (among other applications this includes @nallath and @Ghostkeeper's scanner application and @daid's laser cutter application).

Instead of changing the plugins page in Uranium, you should have removed the Uranium plugins page from the Cura preferences and then add a Cura-specific plugins page in its place, similar to how Cura has a specific General settings page, see https://github.com/Ultimaker/Cura/blob/master/resources/qml/Cura.qml#L508

Remember, the only reason I know this is that I also did this sort of thing wrong, and I was told by the aforementioned people that I broke their stuff.

**Comment by ianpaschal** [comment]
Do you mean the page in the preferences?

**Comment by daid** [comment]
FYI My lasercutter application hasn't been compatible with newer uranium for quite a long time already. Never took the time to update it.

**Comment by fieldOfView** [comment]
Yes, I am talking about PluginsPage.qml

**Comment by ianpaschal** [comment]
Yes, we are aware of that. I made a 5 minute fix and have been working on a more future-proof fix. Will commit when it's of solid quality. I'd also like to refactor the PluginRegistry to actually have the optional ability to fetch a remote plugin list and check for upgrades so that there's neither the creation nor modification of PluginsModels in the PluginBrowser (instead it just displays the given application's single PluginRegistry filtered in different ways).

**Pull request merged**
