### PR TITLE
Add some extra information when the FileWriters can't write the files.

### PR DESCRIPTION
**Pull request by diegopradogesto**
That will give some more information to the user when a message is shown in the frontend.

### CODE REVIEW

**Comment by thopiekar** [comment]
Every time I see setInformation being used, something is send to the Logger, too.
How about moving it to setInformation, too?

**Comment by BagelOrb** [comment]
Looking at the PR it seems that now users will get the message "There is no mesh to save." when they are trying to save the *gcode* before slicing.

Shouldn't there be a separate setInformation in the gcodewriter?

**Comment by diegopradogesto** [comment]
Yes, but it's part of Cura. Here it is: https://github.com/Ultimaker/Cura/pull/4187
@thopiekar I agree, I will do it!

**Comment by thopiekar** [comment]
Great, thanks 😉👍

**Pull request merged**
