### PR TITLE
Relocate locales to proper locations

### PR DESCRIPTION
**Pull request by hroncok**
Fixes https://github.com/Ultimaker/Uranium/issues/246
Fixes https://github.com/Ultimaker/Uranium/issues/277

See https://github.com/Ultimaker/Cura/pull/2342
See https://github.com/Ultimaker/cura-binary-data/pull/8

### CODE REVIEW

**Comment by nallath** [comment]
For our reference; CURA-4263

**Comment by nallath** [comment]
You forgot to do the same for https://github.com/Ultimaker/cura-binary-data

**Comment by hroncok** [comment]
Oh, I didn't know about that one. Will do.

**Comment by hroncok** [comment]
https://github.com/Ultimaker/cura-binary-data/pull/8

**Comment by Ghostkeeper** [comment]
This is a bit more involved, because the language code is also saved in the preferences, and that would mean that the preferences files will have to be upgraded with a version upgrade.

Perhaps it makes sense to change the rest of them also to the xx_XX format instead of leaving the country code out for ones that are not ambiguous.

**Comment by alekseisasin** [comment]
I agree with Ghostkeeper, we need to keep same template for all translations and change rest. 
According to the ISO language_Country codes : https://docs.oracle.com/cd/E13214_01/wli/docs92/xref/xqisocodes.html

German       -> (de_DE)
English        -> (en_EN)
Spanish       -> (es_ES)
Finnish        -> (fi_FI)
French        -> (fr_FR)
Italian          -> (it_IT)
Japanese    -> (ja_JP)
Korean        -> (ko_KR)
Dutch          -> (nl_NL)
Polish          -> (pl_PL)
Portuguese -> (pt_BR)  - Brasil
Russian       -> (ru_RU)
Turkish        -> (tr_TR)
Chinese       -> (zh_CN)

**Comment by hroncok** [comment]
> Perhaps it makes sense to change the rest of them also to the xx_XX format instead of leaving the country code out for ones that are not ambiguous.

It would work, but I don't see the real benefit here.

**Comment by alekseisasin** [comment]
It will help keep structure clear.

**Comment by hroncok** [comment]
OK. My main concern is that all the codes are valid. Other than that, I don't really care.

**Comment by Ghostkeeper** [comment]
I think I'll make the rest of those changes now then, since hroncok has graciously allowed commits to his PR branch :)

**Pull request merged**
