### PR TITLE
Fixing i18n build and install

### PR DESCRIPTION
**Pull request by thopiekar**
* In addition to the pull request at Cura https://github.com/Ultimaker/Cura/pull/576
* Almost does the same as https://github.com/thopiekar/Cura/commit/425a1df865c8063f3f0bf8f2e0c544cd1d1e4536

### CODE REVIEW

**Comment by thopiekar** [comment]
@TMHogenhout ping

**Comment by TMHogenhout** [comment]
That's awesome I just received a ping. :smile: I will check it out (git checkout it) after the weekend.

**Comment by thopiekar** [comment]
Thanks :smile:
By the way, hope you already had and still have a nice weekend!

**Comment by thopiekar** [comment]
Thanks

**Comment by TMHogenhout** [comment]
No thank you. I am working on a readme regarding the translations, it may be of use to you. I'll post the link when it's done.

**Comment by thopiekar** [comment]
I just thanked because it fixes a problem with my packaging at launchpad.net (see https://launchpad.net/~thopiekar/+archive/ubuntu/cura) :smile: 

Ok, thanks :+1:

**Comment by TMHogenhout** [comment]
I expaned the translation guide: https://github.com/Ultimaker/Uranium/blob/2.1/docs/translations.md

**Pull request merged**
