### PR TITLE
New SettingDefinitionsModel

### PR DESCRIPTION
**Pull request by awhiemstra**
This is a reimplementation of SettingDefinitionsModel that is both simpler and faster. It is designed to never trigger a complete model reset apart from containerId or root property changes. In addition, it fixes a number of bugs currently present in the model:

* Children-of-children are visible even if their parents are not
* Empty categories are hidden
* Filtering removes rows instead of hiding the data
* Allow setting the expanded settings so we can re-enable saving and loading of expanded categories.
* Row changes are done through insertRows/removeRows which prevents a complete model reset and only changes things that actually changed.

Additionally this paves the way for creating an "EnabledVisibilityHandler" that modifies visibility based on the enabled property.

### CODE REVIEW

**Comment by sedwards2009** [comment]
@nickthetait  The model referred to here is not the 3D model. The model here is part of the QML UI and the settings sidebar.

**Comment by awhiemstra** [comment]
Yeah, it is the data model class that provides the structure for the sidebar view. Terminology gets kind of confusing with all these different concepts. :)

**Comment by nickthetait** [comment]
Ah, thanks for explaining that.
*starts thinking about how to improve the terminology*

**Comment by fieldOfView** [comment]
@nickthetait: In the code we talk in terms of "meshes" most of the time when we refer to 3d models, to reduce this confusion. In the UI, they are referred to as "objects" (which would also be confusing in the code).

**Comment by nallath** [comment]
This breaks the per-object settings.

**Comment by awhiemstra** [comment]
The actual change needed is really minor: add "expanded: [ "*" ]" to line 156 in PerObjectSettingsPanel.qml. I will push that after this PR is merged since it is rather silly to make an entire branch for just that change.

**Pull request merged**
