### PR TITLE
Fix failing test suite after 435285e

### PR DESCRIPTION
**Pull request by hroncok**
Fixes https://github.com/Ultimaker/Uranium/issues/319

### CODE REVIEW

**Comment by hroncok** [comment]
As a Fedora packager, I have noticed that this is not the first time either Cura or Uranium tests suite is broken after the implementation was updated but the tests were not. Having test without constantly running them is worst than not having them at all (it gives you false idea of safety while there is none).


Could you please consider using some kind of mechanism to prevent this in the future? I.e. some kind of Continues Integration or even Continues Integration with Pull Requests? I consider [Travis CI](https://travis-ci.org/) a perfect service for this kind of stuff, it's also free (both as in free beer and freedom). Thanks.

**Comment by hroncok** [comment]
I see you are using [Jenkins somehow](http://hal9000.ultimaker.com:29130/job/Ultimaker/job/Uranium/job/master/), but it's incredibly hard for me to see whether this was happening or not and when it started.

**Comment by ChrisTerBeke** [comment]
@alekseisasin weren't you working on fixing unit tests?

**Comment by Ghostkeeper** [comment]
Alekseisasin and I fixed the tests because a lot of them also got broken due to this architecture rework: https://github.com/Ultimaker/Uranium/pull/311

We also fixed the tests that got broken from the added file_name parameter and the single extrusion extruder stacks. So this is PR now unnecessary and is giving conflicts because we modified the tests for the same purpose.

**Pull request closed without merging**
