### PR TITLE
[master] Remove debugging message that fills the logs

### PR DESCRIPTION
**Pull request by diegopradogesto**
We don't need to know when a file is not being updated. Also add the `packages.json` file to the list of files that don't need updating.

### CODE REVIEW

**Comment by fieldOfView** [comment]
Actually, I think it is important to log this; it means that these files have an unexpected version, which could mean they have inexpected content too. 

If this occurs often “in the field” it must mean something is potentially corrupting configuration files, and that is something that *should* be logged.

**Comment by fieldOfView** [comment]
I do agree that package.json should be ignored by versionupgraders.

**Comment by diegopradogesto** [comment]
Yes, but it's also outputting messages when the file is up-to-date and it has nothing to upgrade. Then it shows one message for each version upgrade that does nothing with the file.

**Comment by fieldOfView** [comment]
Either way, it is commented-out code, which is against policy.

**Comment by thopiekar** [comment]
I agree with removing dead code, but would remove the debug messages.
Usually, if people find the messages too noisy, then there must be a way to silence them. In case someone needs to debug an error, then there are log parsers to filter the logs.
(We had a ticket in the past about setting the verbosity level, but I think it has never been finished.)

Therefore I agree with @fieldOfView. These lines will be still useful in the future to understand why an upgrade fails or misbehaves.

But yeah, that's only my opinion.

**Comment by diegopradogesto** [comment]
Oh, that commented-out code was my mistake. I was doing tests first and I forgot to actually remove the lines. Done in 95f0525

Regarding if the files are useful or not, I would say that the next log line that says "Create upgrade task for configuration file..." is the one that we want. In case this line is not logged when doing a version upgrade, then something is wrong. I think it is enough.

**Comment by fieldOfView** [comment]
I misread the purpose of this PR, and now agree that it would be a great improvement.

**Pull request merged**
