### PR TITLE
Logger: fixes for logException

### PR DESCRIPTION
**Pull request by thopiekar**
* Don't format lines from traceback
* Directly pass args to self.log()
* Format message only once
* Only format messages when args are passed

Contributes to CURA-1445 and CURA-1771

### CODE REVIEW

**Comment by Ghostkeeper** [comment]
Why was the "Exception: " part of logException removed?

**Comment by thopiekar** [comment]
Good question. I think I've removed it to debug the problem that a %s was left. Would you mind if I write "Exception: " + message, instead of "Exception: %s" %(message)? If we do any modifications on the code in the future it would be easier to find the correct position of incorrect formatting.

**Comment by thopiekar** [comment]
Done

**Comment by thopiekar** [comment]
This PR was missed while working on https://github.com/Ultimaker/Cura/pull/824, which got splitted up.

**Pull request merged**
