### PR TITLE
i18n: de: Another set of translation improvements

### PR DESCRIPTION
**Pull request by thopiekar**
Needed for PR: https://github.com/Ultimaker/Cura/pull/629

### CODE REVIEW

**Comment by Ghostkeeper** [comment]
I'll redo the update for the .mo files shortly.

**Comment by thopiekar** [comment]
Ah, OK, but you mean the po files I guess. mo are the compiled files :)

**Comment by Ghostkeeper** [comment]
No, I meant the compiled files. We haven't set up yet that these are compiled automatically by https://github.com/Ultimaker/cura-build, so they still have to get updated manually into the https://github.com/Ultimaker/cura-binary-data repository. The reason for that is that we didn't want to depend on the extra programs that compile the .po files, which are platform-specific again and such.

**Comment by Ghostkeeper** [comment]
.mo files have been updated.

**Pull request merged**
