### PR TITLE
improve Japanese localization

### PR DESCRIPTION
**Pull request by h1data**
Improving Japanese localization for Cura [issue#19438](https://github.com/Ultimaker/Cura/issues/19438)

Compiled uranium.po to mo file and checked the view of the application.

### CODE REVIEW

**Comment by h1data** [comment]
After opening this PR, I've got notification about unit test was failed.
What should I do?
image

**Comment by wawanbreton** [comment]
I have manually merged this branch to https://github.com/Ultimaker/Uranium/pull/972, @h1data please check that I didn't do any mistake, I had some conflicts but I think it is fine.

**Comment by h1data** [comment]
@wawanbreton Thanks, I checked po file in lokalise-2024-10-14_09-02-46 branch
and all changes are included, so it's OK!

**Comment by wawanbreton** [comment]
Great, thanks for the feedback :slightly_smiling_face:

**Pull request closed without merging**
