### PR TITLE
Prevent selected children of selected nodes being transformed twice

### PR DESCRIPTION
**Pull request by fieldOfView**
This PR fixes an issue where if the user selects both a child object and its parent, the child object effectively gets transformed twice. 

Steps to reproduce:
* load two objects
* group the two objects
* select the group AND one of the children (ctrl+shift-click the child)
* move/rotate/scale the selection

Expected result:
The group is transformed, and the child is automatically transformed by its parenting in the scene graph

Actual result:
The group is transformed, the child is transformed twice as much as the group

Additional info:
The issue also affects Support Eraser meshes

### CODE REVIEW

**Comment by fieldOfView** [comment]
@Vandrasc, this fixes "that issue" we talked about on "that channel" which I don't have access to anymore.

**Comment by nallath** [comment]
CURA-5152

**Comment by ianpaschal** [comment]
I'm getting a crash when trying to select an object:

```
2018-03-26 15:07:29,626 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [66]: An uncaught error has occurred!
2018-03-26 15:07:29,634 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]: Traceback (most recent call last):
2018-03-26 15:07:29,634 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "/Users/i.paschal/Code/Ultimaker/Uranium/UM/Qt/Bindings/MainWindow.py", line 148, in mousePressEvent
2018-03-26 15:07:29,635 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:     self._mouse_device.handleEvent(event)
2018-03-26 15:07:29,635 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "/Users/i.paschal/Code/Ultimaker/Uranium/UM/Qt/QtMouseDevice.py", line 24, in handleEvent
2018-03-26 15:07:29,635 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:     self.event.emit(e)
2018-03-26 15:07:29,635 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "/Users/i.paschal/Code/Ultimaker/Uranium/UM/Signal.py", line 212, in emit
2018-03-26 15:07:29,636 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:     self.__performEmit(*args, **kwargs)
2018-03-26 15:07:29,636 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "/Users/i.paschal/Code/Ultimaker/Uranium/UM/Signal.py", line 315, in __performEmit
2018-03-26 15:07:29,636 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:     func(dest, *args, **kwargs)
2018-03-26 15:07:29,636 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "/Users/i.paschal/Code/Ultimaker/Uranium/UM/Controller.py", line 325, in event
2018-03-26 15:07:29,637 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:     if self._selection_tool and self._selection_tool.event(event):
2018-03-26 15:07:29,637 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "/Users/i.paschal/Code/Ultimaker/Uranium/UM/../plugins/Tools/SelectionTool/SelectionTool.py", line 67, in event
2018-03-26 15:07:29,637 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:     self._pixelSelection(event)
2018-03-26 15:07:29,637 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "/Users/i.paschal/Code/Ultimaker/Uranium/UM/../plugins/Tools/SelectionTool/SelectionTool.py", line 143, in _pixelSelection
2018-03-26 15:07:29,638 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:     Selection.add(node)
2018-03-26 15:07:29,638 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "/Users/i.paschal/Code/Ultimaker/Uranium/UM/Scene/Selection.py", line 26, in add
2018-03-26 15:07:29,638 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:     cls.selectionChanged.emit()
2018-03-26 15:07:29,638 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "/Users/i.paschal/Code/Ultimaker/Uranium/UM/Signal.py", line 212, in emit
2018-03-26 15:07:29,638 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:     self.__performEmit(*args, **kwargs)
2018-03-26 15:07:29,639 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "/Users/i.paschal/Code/Ultimaker/Uranium/UM/Signal.py", line 315, in __performEmit
2018-03-26 15:07:29,639 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:     func(dest, *args, **kwargs)
2018-03-26 15:07:29,639 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "/Users/i.paschal/Code/Ultimaker/Cura/cura/CuraApplication.py", line 933, in onSelectionChanged
2018-03-26 15:07:29,639 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:     self.getController().setActiveTool("TranslateTool")
2018-03-26 15:07:29,639 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "/Users/i.paschal/Code/Ultimaker/Uranium/UM/Controller.py", line 268, in setActiveTool
2018-03-26 15:07:29,640 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:     self._active_tool.event(ToolEvent(ToolEvent.ToolActivateEvent))
2018-03-26 15:07:29,640 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "/Users/i.paschal/Code/Ultimaker/Uranium/UM/../plugins/Tools/TranslateTool/TranslateTool.py", line 197, in event
2018-03-26 15:07:29,640 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:     for node in self._getSelectedObjectsWithoutSelectedAncestors():
2018-03-26 15:07:29,640 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "/Users/i.paschal/Code/Ultimaker/Uranium/UM/Tool.py", line 176, in _getSelectedObjectsWithoutSelectedAncestors
2018-03-26 15:07:29,640 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:     return result
2018-03-26 15:07:29,640 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]: NameError: name 'result' is not defined
```

**Comment by fieldOfView** [comment]
I'm sorry, I forgot to commit a fix that was necessitated by a refactor of my tested implementation. Should work now.

**Pull request merged**
