### PR TITLE
Remember the last used output device between sessions

### PR DESCRIPTION
**Pull request by fieldOfView**
This PR adds a preference to the OutputDeviceManager to remember which outputdevice is selected between sessions.

https://github.com/Ultimaker/Cura/issues/7168

### CODE REVIEW

**Comment by fieldOfView** [comment]
`TestOutputDeviceManager` will have to be fixed.

I'm not sure if there is a better way to access the Application object (which is needed to reach the Preferences object and to delay restoring the active output device until after the output device plugins have loaded). If there is, the signature of OutputDevice() would not have to change.

**Comment by fieldOfView** [comment]
Hmm, simple as this PR is, it needs some more work; UM.Application does not have a signal I can use to wait until all outputdeviceplugins have loaded, and we don't want to tie the OutputDeviceManager to UM.QTApplication.

Perhaps this should live in the OutputDeviceManagerProxy, which is already tied to Qt.

**Comment by fieldOfView** [comment]
Changed to a much cleaner implementation in `OutputDeviceManagerProxy`

**Comment by rburema** [comment]
Devs: Refer to internal ticket CURA-7335 for this PR.

**Pull request merged**
